[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["DISABLE_ESLINT_PLUGIN=true yarn build"]

[start]
cmd = "npx serve -s build -l ${PORT:-3000}"
